project_id: "620320"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # JSON 翻译文件
  - source: /src/locales/zh-CN/**/*
    translation: /src/locales/%locale%/**/%original_file_name%
